---
# Source: cadvisor/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cadvisor
  namespace: nodegroup
---
# Source: cadvisor/templates/operator-deployment.yaml
apiVersion: apps.kubeedge.io/v1alpha1
kind: EdgeApplication
metadata:
  name: cadvisor
  labels:
    app.kubernetes.io/name: cadvisor
  namespace: nodegroup
spec:
  workloadTemplate:
    manifests:
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          namespace: nodegroup
          name: cadvisor
          labels:
            app.kubernetes.io/name: cadvisor
            app.kubernetes.io/instance: cadvisor
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/component: operator
            helm.sh/chart: cadvisor-0.1.0
            app.kubernetes.io/version: "0.1.0"
          annotations:
            seccomp.security.alpha.kubernetes.io/pod: docker/default
        spec:
          replicas: 1
          selector:
            matchLabels:
              app.kubernetes.io/name: cadvisor
              app.kubernetes.io/instance: cadvisor
          template:
            metadata:
              labels:
                app.kubernetes.io/name: cadvisor
                app.kubernetes.io/instance: cadvisor
            spec:
              serviceAccountName: cadvisor
              containers:
                - name: cadvisor
                  image: "gcr.io/cadvisor/cadvisor:v0.45.0"
                  imagePullPolicy: IfNotPresent
                  env:
                    - name: NODE_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: spec.nodeName
                  resources:
                    limits:
                      cpu: 800m
                      memory: 2000Mi
                    requests:
                      cpu: 400m
                      memory: 400Mi
                  volumeMounts:
                    - name: rootfs
                      mountPath: /rootfs
                      readOnly: true
                    - name: var-run
                      mountPath: /var/run
                      readOnly: true
                    - name: sys
                      mountPath: /sys
                      readOnly: true
                    - name: docker
                      mountPath: /var/lib/docker
                      readOnly: true
                    - name: disk
                      mountPath: /dev/disk
                      readOnly: true
                  ports:
                    - name: http
                      containerPort: 8080
                      protocol: TCP
                  args:
              volumes:
                - name: rootfs
                  hostPath:
                    path: /
                - name: var-run
                  hostPath:
                    path: /var/run
                - name: sys
                  hostPath:
                    path: /sys
                - name: docker
                  hostPath:
                    path: /var/lib/docker
                - name: disk
                  hostPath:
                    path: /dev/disk
              tolerations:
                - effect: NoExecute
                  key: edgefarm.applications
                  operator: Exists
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                      - matchExpressions:
                          - key: node-role.kubernetes.io/edge
                            operator: Exists
      - apiVersion: v1
        kind: Service
        metadata:
          name: cadvisor
          namespace: nodegroup
          labels:
            app.kubernetes.io/name: cadvisor
            app.kubernetes.io/instance: cadvisor
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/component: operator
            helm.sh/chart: cadvisor-0.1.0
            app.kubernetes.io/version: "0.1.0"
        spec:
          type:
          ports:
            - port: 8080
              targetPort: 8080
              protocol: TCP
              name: http
          selector:
            app.kubernetes.io/name: cadvisor
            app.kubernetes.io/instance: cadvisor
  workloadScope:
    targetNodeGroups:
      - name: virtual-88934dbb
      - name: virtual-e8c1df83
