apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-nodegroup-to-monitoring
  annotations:
    policies.kyverno.io/title: add-nodegroup-to-monitoring
    policies.kyverno.io/description: >-
      Adds the nodegroup to the edge monitoring resources if a new edge node is added.
spec:
  background: true
  rules:
    - name: add-to-edge-monitoring
      match:
        any:
          - resources:
              kinds:
                - Node
              selector:
                matchLabels:
                  node-role.kubernetes.io/edge: ""
      preconditions:
        all:
          - key: "{{ request.operation || 'BACKGROUND' }}"
            operator: In
            value:
              - CREATE
              - UPDATE
      mutate:
        targets:
          - apiVersion: apps.kubeedge.io/v1alpha1
            kind: EdgeApplication
            name: grafana-agent
            namespace: nodegroup
          - apiVersion: apps.kubeedge.io/v1alpha1
            kind: EdgeApplication
            name: node-exporter
            namespace: nodegroup
        patchesJson6902: |-
          - op: add
            path: "/spec/workloadScope/targetNodeGroups/-"
            value: {"name": "{{request.object.metadata.name}}"}
