version: v2beta1
name: edgefarm-network

vars:
  monitoring_password_dir:
    command: echo $HOME/.devspace/edgefarn.monitor/monitoring_password/
  monitoring_password:
    command: |-
      #!/bin/bash
      set -e
      echo $(cat ${monitoring_password_dir}/password)
  monitoring_user:
    value: edgefarm-monitor

functions:
  init_monitoring_password: |-
    # usage init_monitoring_password <DIR>
    #!/usr/bin/env bash
    set -e
    set -u
    if [ "$#" -ne 1 ]; then
      echo "Illegal number of parameters"
      echo "monitoring_password_psk"
      exit 1
    fi
    if ! [ -f "${1}/password" ]; then
      echo "generating password in ${1}"
      mkdir -p ${1}
      date +%s | sha256sum | base64 | head -c 32 > ${1}/password
    fi

pipelines:
  init: |-
    # generating password for monitoring
    init_monitoring_password ${monitoring_password_dir}

  # deploy-node-exporter: |-
  #   # deploy node exporter
  #   create_deployments node-exporter
  #   create_deployments service-monitor-for-node-exporter

  deploy-monitoring: |-
    # install all monitoring setup: grafana, grafana-operator and mimir
    create_deployments prometheus-crd
    create_deployments grafana
    create_deployments grafana-mimir
    create_deployments grafana-agent-operator

    # install main-nats monitoring
    create_deployments main-nats-monitoring

    # install edge grafana-agent, node-exporter and cadvisor
    create_deployments edge-node-exporter
    create_deployments edge-cadvisor
    create_deployments edge-grafana-agent

deployments:
  grafana-mimir:
    helm:
      chart:
        name: mimir-distributed
        repo: https://grafana.github.io/helm-charts
        version: "3.3.0"
      values:
        nginx:
          basicAuth:
            enabled: false
            username: ${mimir_user}
            password: ${mimir_password}
            htpasswd: >-
              {{ htpasswd (required "'nginx.basicAuth.username' is required" .Values.nginx.basicAuth.username) (required "'nginx.basicAuth.password' is required" .Values.nginx.basicAuth.password) }}
        metaMonitoring:
          serviceMonitor:
            enabled: true
            namespace: monitoring
          grafanaAgent:
            metrics:
              enabled: true
              remote:
                url: "http://grafana-mimir-nginx.monitoring.svc:80/api/v1/push"
    namespace: monitoring

  grafana:
    helm:
      chart:
        name: grafana
        version: "6.44.0"
        repo: https://grafana.github.io/helm-charts
      valuesFiles:
        - ./dev/charts/grafana/values.yaml
      values:
        datasources:
          datasources.yaml:
            datasources:
              - name: mimir
                type: prometheus
                url: http://grafana-mimir-nginx.monitoring.svc:80/prometheus
                access: proxy
                basicAuth: true
                basicAuthUser: ${mimir_user}
                withCredentials: true
                isDefault: true
                editable: true
                secureJsonData:
                  basicAuthPassword: ${mimir_password}
    namespace: monitoring

  edge-node-exporter:
    helm:
      chart:
        name: ./charts/node-exporter
    namespace: edge-monitoring

  edge-grafana-agent:
    helm:
      chart:
        name: ./charts/grafana-agent/
      values:
        configmap:
          agent_yaml:
            metrics:
              configs:
                edgenodes_exporter:
                  remote_write:
                    basic_auth:
                      username: ${monitoring_user}
                      password: ${monitoring_password}
            logs:
              configs:
                default:
                  clients:
                    basic_auth:
                      username: ${monitoring_user}
                      password: ${monitoring_password}
    namespace: edge-monitoring

  edge-cadvisor:
    helm:
      chart:
        name: ./charts/cadvisor/
    namespace: edge-monitoring

  prometheus-crd:
    kubectl:
      manifests:
        - https://raw.githubusercontent.com/grafana/agent/main/production/operator/crds/monitoring.coreos.com_podmonitors.yaml
        - https://raw.githubusercontent.com/grafana/agent/main/production/operator/crds/monitoring.coreos.com_probes.yaml
        - https://raw.githubusercontent.com/grafana/agent/main/production/operator/crds/monitoring.coreos.com_servicemonitors.yaml
        - https://raw.githubusercontent.com/grafana/agent/main/production/operator/crds/monitoring.grafana.com_grafanaagents.yaml
        - https://raw.githubusercontent.com/grafana/agent/main/production/operator/crds/monitoring.grafana.com_integrations.yaml
        - https://raw.githubusercontent.com/grafana/agent/main/production/operator/crds/monitoring.grafana.com_logsinstances.yaml
        - https://raw.githubusercontent.com/grafana/agent/main/production/operator/crds/monitoring.grafana.com_metricsinstances.yaml
        - https://raw.githubusercontent.com/grafana/agent/main/production/operator/crds/monitoring.grafana.com_podlogs.yaml
    namespace: monitoring

  grafana-agent-operator:
    helm:
      chart:
        name: grafana-agent-operator
        repo: https://grafana.github.io/helm-charts
        version: "0.2.8"
      values: {}
    namespace: monitoring

  main-nats-monitoring:
    helm:
      chart:
        name: main-nats-monitoring
        path: ./charts/main-nats-monitoring
      values:
        mimir:
          user: ${monitoring_user}
          password: ${monitoring_password}
        agent:
          image: grafana/agent:v0.28.0
    namespace: monitoring

  # Old setup we will need in future. Don't delete it yet
  # node-exporter:
  #   helm:
  #     chart:
  #       name: prometheus-node-exporter
  #       repo: https://prometheus-community.github.io/helm-charts
  #     valuesFiles:
  #       - ./dev/charts/node-exporter/values.yaml
  #   namespace: monitoring

  # service-monitor-for-node-exporter:
  #   kubectl:
  #     manifests:
  #       - ./dev/charts/node-exporter/service-monitor.yaml
  #   namespace: monitoring
