version: v2beta1

pipelines:
  deploy-agent: |-
    # install grafana grafana agent
    create_deployments monitoiring-secret-for-grafana-agent
    create_deployments grafana-agent
    create_deployments monitoiring-resources-for-nats
    
  deploy-nats: |-
    # deploy nats
    create_deployments nats
    
  deploy-node-exporter: |-
    # deploy node exporter
    create_deployments node-exporter
    create_deployments service-monitor-for-node-exporter

  deploy-mimir-grafana: |-
    # install grafana and mimir
    create_deployments grafana
    create_deployments grafana-mimir

  deploy-monitoring: |-
    # install all monitoring setup
    run_pipelines deploy-agent
    run_pipelines deploy-nats deploy-node-exporter
    run_pipelines deploy-mimir-grafana

deployments:
  grafana-mimir:
    helm:
      chart:
        name: mimir-distributed
        repo: https://grafana.github.io/helm-charts 
      valuesFiles: 
      - ./dev/charts/mimir/values.yaml
    namespace: monitoring

  grafana:
    helm:
      chart:
        name: grafana
        repo: https://grafana.github.io/helm-charts 
      valuesFiles: 
      - ./dev/charts/grafana/values.yaml
    namespace: monitoring

  grafana-agent:
    helm:
      chart:
        name: grafana-agent-operator
        repo: https://grafana.github.io/helm-charts
      valuesFiles: 
      - ./dev/charts/grafana-agent/values.yaml
    namespace: monitoring

  monitoiring-secret-for-grafana-agent:
    kubectl:
      manifests:
        - ./dev/charts/grafana-agent/secret.yaml
    namespace: monitoring

  nats:
    helm:
      chart:
        name: nats
        repo: https://nats-io.github.io/k8s/helm/charts/
      valuesFiles: 
      - ./dev/charts/nats/values.yaml
    namespace: nats

  node-exporter:
    helm:
      chart:
        name: prometheus-node-exporter
        repo: https://prometheus-community.github.io/helm-charts
      valuesFiles: 
      - ./dev/charts/node-exporter/values.yaml
    namespace: monitoring

  service-monitor-for-node-exporter:
    kubectl:
      manifests:
        - ./dev/charts/node-exporter/service-monitor.yaml
    namespace: monitoring


  monitoiring-resources-for-nats:
    kubectl:
      manifests:
        - ./dev/charts/grafana-agent/nats_metric_instance.yaml
        - ./dev/charts/grafana-agent/rbac_grafana_agent.yaml
        - ./dev/charts/grafana-agent/nats_grafana_agent.yaml
    namespace: monitoring
