version: v2beta1

pipelines:
  deploy-agent: |-
    # install grafana agent
    create_deployments monitoring-secret-for-grafana-agent
    create_deployments grafana-agent
    create_deployments monitoring-resources-for-nats

  deploy-nats: |-
    # deploy nats
    create_deployments nats

  deploy-node-exporter: |-
    # deploy node exporter
    create_deployments node-exporter
    create_deployments service-monitor-for-node-exporter

  deploy-monitoring: |-
    # install grafana mimir
    create_deployments grafana
    create_deployments grafana-mimir

deployments:
  grafana-mimir:
    helm:
      chart:
        name: mimir-distributed
        repo: https://grafana.github.io/helm-charts
      valuesFiles:
      - ./charts/mimir/values.yaml
    namespace: monitoring

  grafana:
    helm:
      chart:
        name: grafana
        repo: https://grafana.github.io/helm-charts
      valuesFiles:
      - ./charts/grafana/values.yaml
    namespace: monitoring

  grafana-agent:
    helm:
      chart:
        name: grafana-agent-operator
        repo: https://grafana.github.io/helm-charts
      valuesFiles:
      - ./charts/grafana-agent/values.yaml
    namespace: monitoring

  monitoring-secret-for-grafana-agent:
    kubectl:
      manifests:
        - ./charts/grafana-agent/secret.yaml
    namespace: monitoring

  nats:
    helm:
      chart:
        name: nats
        repo: https://nats-io.github.io/k8s/helm/charts/
      valuesFiles:
      - ./charts/nats/values.yaml
    namespace: nats

  node-exporter:
    helm:
      chart:
        name: prometheus-node-exporter
        repo: https://prometheus-community.github.io/helm-charts
      valuesFiles:
      - ./charts/node-exporter/service-monitor.yaml
    namespace: monitoring

  service-monitor-for-node-exporter:
    kubectl:
      manifests:
        - ./charts/grafana-agent/nats_metric_instance.yaml
    namespace: monitoring


  monitoring-resources-for-nats:
    kubectl:
      manifests:
        - ./charts/grafana-agent/nats_metric_instance.yaml
        - ./charts/grafana-agent/rbac_grafana_agent.yaml
        - ./charts/grafana-agent/nats_grafana_agent.yaml
    namespace: monitoring
