apiVersion: v1
kind: Node
metadata: 
  annotations: 
    node.alpha.kubernetes.io/ttl: "0"
  labels: 
    apps.kubeedge.io/belonging-to: swordfish
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    edgefarm.io/node: swordfish
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: swordfish
    kubernetes.io/os: linux
    node-role.kubernetes.io/agent: ""
    node-role.kubernetes.io/edge: ""
  name: swordfish
spec: 
  podCIDR: 10.244.7.0/24
  podCIDRs: 
  - 10.244.7.0/24
  taints: 
  - effect: NoExecute
    key: edgefarm.applications
