apiVersion: monitoring.grafana.com/v1alpha1
kind: GrafanaAgent
metadata:
  name: {{ include "main-nats-monitoring.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  image: grafana/agent:v0.28.0
  logLevel: info
  serviceAccountName: {{ include "main-nats-monitoring.name" . }}
  metrics:
    instanceSelector:
      matchLabels:
        app.kubernetes.io/component: meta-monitoring
        app.kubernetes.io/instance: {{ include "main-nats-monitoring.name" . }}
        app.kubernetes.io/name: mimir
    externalLabels:
      cluster: cloud
  logs:
    instanceSelector:
      matchLabels:
        agent: grafana-agent-logs
