apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "main-nats-monitoring.name" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "main-nats-monitoring.name" . }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - nodes/metrics
  - services
  - endpoints
  - pods
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  - /metrics/cadvisor
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "main-nats-monitoring.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "main-nats-monitoring.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "main-nats-monitoring.name" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
