{{- if and .Values.rbac.create .Values.rbac.pspEnabled (.Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: psp-{{ template "node-exporter.fullname" . }}
  labels: {{ include "node-exporter.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp-{{ template "node-exporter.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "node-exporter.fullname" . }}
    namespace: {{ template "node-exporter.namespace" . }}
{{- end }}
