{{- if .Values.rbac.create -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "node-exporter.serviceAccountName" . }}
  namespace: {{ template "node-exporter.namespace" . }}
  labels: {{ include "node-exporter.labels" . | indent 4 }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
imagePullSecrets:
{{ toYaml .Values.serviceAccount.imagePullSecrets | indent 2 }}
{{- end -}}
{{- end -}}
