apiVersion: monitoring.grafana.com/v1alpha1
kind: MetricsInstance
metadata:
  name: nats
  namespace: default
  labels:
    # app.kubernetes.io/name: nats
    app.kubernetes.io/component: meta-monitoring
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/name: mimir
spec:
  remoteWrite:
    - url: http://mimir-nginx.default.svc:80/api/v1/push
  serviceMonitorNamespaceSelector: {}
    # matchLabels:
    #   # instance: primary
    #   app.kubernetes.io/name: default
  serviceMonitorSelector: {}
  # serviceMonitorSelector:
  #   matchLabels:
  #     app.kubernetes.io/managed-by: Helm
      # app.kubernetes.io/name: mimir
    # matchLabels:
    #   # instance: primary
    #   app.kubernetes.io/managed-by: Helm
    # basicAuth:
    #   username:
    #     name: primary-credentials-metrics
    #     key: username
    #   password:
    #     name: primary-credentials-metrics
    #     key: password
  #  labels:                                                                                                                                                                                                                                                                                                                                                                         │
  #     app.kubernetes.io/name: ingress-nginx

  #  labels:
  #    app.kubernetes.io/name: ingress-nginx