apiVersion: monitoring.grafana.com/v1alpha1
kind: GrafanaAgent
metadata:
  name: grafana-agent
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: grafana-agent
spec:
  image: grafana/agent:v0.28.0
  logLevel: info
  serviceAccountName: grafana-agent
  metrics:
    instanceSelector:
      matchLabels:
        app.kubernetes.io/component: meta-monitoring
        app.kubernetes.io/instance: grafana-mimir
        app.kubernetes.io/name: mimir
    externalLabels:
      cluster: cloud
  logs:
    instanceSelector:
      matchLabels:
        agent: grafana-agent-logs