apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: my-nats
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
    - apiVersion: monitoring.coreos.com/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
        f:spec:
          .: {}
          f:endpoints: {}
          f:namespaceSelector:
            .: {}
            f:any: {}
          f:selector:
            .: {}
            f:matchLabels:
              .: {}
              f:app.kubernetes.io/instance: {}
              f:app.kubernetes.io/name: {}
      manager: helm
      operation: Update
      time: '2022-10-05T14:03:42Z'
  name: my-nats
  namespace: default
spec:
  endpoints:
    - path: /metrics
      port: metrics
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/instance: my-nats
      app.kubernetes.io/name: nats
