apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: mimir
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/component: nats
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mimir
    app.kubernetes.io/part-of: memberlist
    app.kubernetes.io/version: 2.3.1
    helm.sh/chart: mimir-distributed-3.1.0
  name: mimir-nats
  namespace: default
spec:
  endpoints:
  - port: metrics
    # relabelings:
    # - action: replace
    #   replacement: default/querier
    #   sourceLabels:
    #   - job
    #   targetLabel: job
    # - action: replace
    #   replacement: mimir
    #   targetLabel: cluster
    scheme: http
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchExpressions:
    - key: prometheus.io/service-monitor
      operator: NotIn
      values:
      - "false"
    matchLabels:
      # app.kubernetes.io/component: querier
      # app.kubernetes.io/instance: mimir
      # app.kubernetes.io/name: mimir
  # labels:
      app.kubernetes.io/instance: my-nats
    # app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: nats
    # app.kubernetes.io/version: 2.9.0
    # helm.sh/chart: nats-0.18.0