apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: mimir
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/component: nats
    app.kubernetes.io/instance: grafana-mimir
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana-mimir
    app.kubernetes.io/part-of: memberlist
    app.kubernetes.io/version: 2.3.1
    helm.sh/chart: mimir-distributed-3.1.0
  name: mimir-nats
  namespace: monitoring
spec:
  endpoints:
  - port: metrics
    scheme: http
  namespaceSelector: {}
  selector:
    matchLabels:
      app.kubernetes.io/instance: nats
      app.kubernetes.io/name: nats
