---
# Source: grafana-agent-operator/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-agent-yml
  namespace: nodegroup
  labels:
    k8s-app: grafana-agent
data:
  agent.yaml: |
    server:
      log_level: info
    metrics:
      global:
        scrape_interval: 1m
        remote_write:
          - url: http://192.168.1.91:9009/api/v1/push
      configs:
        - name: default
          scrape_configs:
            - job_name: agent
              static_configs:
                - targets: 10.96.214.78:9100
          remote_write:
            - url:
---
# Source: grafana-agent-operator/templates/operator-deployment.yaml
apiVersion: apps.kubeedge.io/v1alpha1
kind: EdgeApplication
metadata:
  name: grafana-agent
  labels: 
    app.kubernetes.io/name: grafana-agent
  namespace: nodegroup
spec:
  workloadTemplate:
    manifests:
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          namespace: nodegroup
          name: grafana-agent-grafana-agent-operator
          labels:
            app.kubernetes.io/name: grafana-agent-operator
            app.kubernetes.io/instance: grafana-agent
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/component: operator
            helm.sh/chart: grafana-agent-operator-0.2.8
            app.kubernetes.io/version: "0.28.0"
        spec:
          replicas: 1
          selector:
            matchLabels:
              app.kubernetes.io/name: grafana-agent-operator
              app.kubernetes.io/instance: grafana-agent
          template:
            metadata:
              labels:
                app.kubernetes.io/name: grafana-agent-operator
                app.kubernetes.io/instance: grafana-agent
            spec:
              containers:
              - name: grafana-agent-operator
                image: "docker.io/grafana/agent:v0.28.0"
                imagePullPolicy: IfNotPresent
                volumeMounts: 
                  - name: agent-yaml
                    mountPath: /etc/agent/
                args:
              volumes:
                - name: agent-yaml
                  configMap: 
                    name: grafana-agent-yml
              tolerations:
                - effect: NoExecute
                  key: edgefarm.applications
                  operator: Exists
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: node-role.kubernetes.io/edge
                        operator: Exists
  workloadScope:
    targetNodeGroups:
      - name: virtual-25af4f51
      - name: virtual-3da802e0
      - name: virtual-e2ddb58a
