{{- $fixedEnabled := .Values.config.grafana.adminCreds.secret.content.fixed.enabled }}
{{- $externalSecretEnabled := .Values.config.grafana.adminCreds.secret.content.externalSecret.enabled }}

{{- if and $fixedEnabled $externalSecretEnabled }}
  {{- fail "Both config.grafana.adminCreds.secret.content.fixed and config.grafana.adminCreds.secret.content.externalSecret are enabled. Only one should be enabled." }}
{{- else if and (not $fixedEnabled) (not $externalSecretEnabled) }}
  {{- fail "Neither config.grafana.adminCreds.secret.content.fixed nor config.grafana.adminCreds.secret.content.externalSecret are enabled. One should be enabled." }}
{{- end }}

{{- if $externalSecretEnabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.config.grafana.adminCreds.secret.name}}
  labels:
    {{- include "edgefarm-monitor.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: {{ .Values.config.grafana.adminCreds.secret.content.externalSecret.kind }}
    name: {{ .Values.config.grafana.adminCreds.secret.content.externalSecret.name }}
  target:
    name: {{ .Values.config.grafana.adminCreds.secret.name}}
    template:
      engineVersion: v2
      data:
        {{ .Values.config.grafana.adminCreds.secret.userKey }}: "{{`{{`}} .{{ .Values.config.grafana.adminCreds.secret.userKey }} }}"
        {{ .Values.config.grafana.adminCreds.secret.passwordKey }}: "{{`{{`}} .{{ .Values.config.grafana.adminCreds.secret.passwordKey }} }}"
  data:
    - secretKey: {{ .Values.config.grafana.adminCreds.secret.userKey }}
      remoteRef:
        key: {{ .Values.config.grafana.adminCreds.secret.content.externalSecret.remoteUserKey }}
    - secretKey: {{ .Values.config.grafana.adminCreds.secret.passwordKey }}
      remoteRef:
        key: {{ .Values.config.grafana.adminCreds.secret.content.externalSecret.remotePasswordKey}}
{{- end }}

{{- if  $fixedEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.grafana.adminCreds.secret.name }}
  labels:
    app: grafana
    grafana: admin-creds
    {{- include "edgefarm-monitor.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ .Values.config.grafana.adminCreds.secret.userKey }}: {{ .Values.config.grafana.adminCreds.secret.content.fixed.adminUser | b64enc | quote }}
  {{ .Values.config.grafana.adminCreds.secret.passwordKey }}: {{ .Values.config.grafana.adminCreds.secret.content.fixed.adminPassword | b64enc | quote }}
{{- end }}
