{{- if .Values.config.certificateIssuer.create }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.config.certificateIssuer.name }}
  labels:
    {{- include "edgefarm-monitor.labels" . | nindent 4 }}
spec:
{{ .Values.config.certificateIssuer.spec | toYaml | indent 2 }}
{{- end }}
