# kind: Secret
# apiVersion: v1
# metadata:
#   name: mimir-datasource
#   namespace: monitoring
#   labels:
#     grafana_datasource: test
# data:
#   datasources.yaml: >-
#     YXBpVmVyc2lvbjogMQpkYXRhc291cmNlczoKLSBhY2Nlc3M6IHByb3h5CiAgYmFzaWNBdXRoOiB0cnVlCiAgYmFzaWNBdXRoUGFzc3dvcmQ6IHRlc3QKICBiYXNpY0F1dGhVc2VyOiBuYXRzCiAgZWRpdGFibGU6IHRydWUKICBpc0RlZmF1bHQ6IHRydWUKICBuYW1lOiBtaW1pcgogIHR5cGU6IHByb21ldGhldXMKICB1cmw6IGh0dHA6Ly9ncmFmYW5hLW1pbWlyLW5naW54Lm1vbml0b3Jpbmcuc3ZjOjgwL3Byb21ldGhldXM=
# type: Opaque
