ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
  labels: {}
  path: /

  pathType: Prefix

  hosts:
    - grafana.10-5-0-30.nip.io

datasources:
 datasources.yaml:
   apiVersion: 1
   datasources:
   - name: mimir
     type: prometheus
     url: http://grafana-mimir-nginx.monitoring.svc:80/prometheus
     access: proxy
     basicAuth: true
     basicAuthUser: nats
     withCredentials: true
     isDefault: true
     editable: true
     secureJsonData:
       basicAuthPassword: test

dashboardProviders:
 dashboardproviders.yaml:
   apiVersion: 1
   providers:
   - name: 'default'
     orgId: 1
     folder: ''
     type: file
     disableDeletion: false
     editable: true
     options:
       path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    nats-dashboard:
      url: https://raw.githubusercontent.com/edgefarm/grafana-dashboards/feature_add_dashboards/dashboards/nats.json
      token: ''
    node-exporter-dashboard:
      url: https://raw.githubusercontent.com/edgefarm/grafana-dashboards/feature_add_dashboards/dashboards/node_exporter.json
      token: ''

#if you want persistend disk 
# persistence:
#   type: pvc
#   enabled: true
#   # storageClassName: default
#   accessModes:
#     - ReadWriteOnce
#   size: 1Gi
#   # annotations: {}
#   finalizers:
#     - kubernetes.io/pvc-protection