apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  namespace: kube-system
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /john
            pathType: Prefix
            backend:
              service:
                name: hello-world-app
                port:
                  number: 80
    - host: localhost
      http:
        paths:
          - path: /jane
            pathType: Prefix
            backend:
              service:
                name: hello-world-app
                port:
                  number: 80
