---
# Source: prometheus-node-exporter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-exporter-prometheus-node-exporter
  namespace: nodegroup
  labels:     
    helm.sh/chart: prometheus-node-exporter-4.4.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: prometheus-node-exporter
    app.kubernetes.io/instance: node-exporter
    app.kubernetes.io/name: prometheus-node-exporter
    app.kubernetes.io/version: "1.3.1"
  annotations:
    {}
imagePullSecrets:
  []
---
# Source: prometheus-node-exporter/templates/edgeapplication.yaml
apiVersion: apps.kubeedge.io/v1alpha1
kind: EdgeApplication
metadata:
  name: node-exporter
  labels: 
    app.kubernetes.io/name: prometheus-node-exporter
  namespace: nodegroup
spec:
  workloadTemplate:
    manifests:
     - apiVersion: apps/v1
       kind: Deployment
       metadata:
         name: node-exporter-prometheus-node-exporter
         namespace: nodegroup
         labels:            
           helm.sh/chart: prometheus-node-exporter-4.4.1
           app.kubernetes.io/managed-by: Helm
           app.kubernetes.io/component: metrics
           app.kubernetes.io/part-of: prometheus-node-exporter
           app.kubernetes.io/instance: node-exporter
           app.kubernetes.io/name: prometheus-node-exporter
           app.kubernetes.io/version: "1.3.1"
       spec:
         selector:
           matchLabels:             
             app.kubernetes.io/instance: node-exporter
             app.kubernetes.io/name: prometheus-node-exporter
         strategy:
           rollingUpdate:
             maxUnavailable: 1
           type: RollingUpdate
         template:
           metadata:
             labels:                  
                 helm.sh/chart: prometheus-node-exporter-4.4.1
                 app.kubernetes.io/managed-by: Helm
                 app.kubernetes.io/component: metrics
                 app.kubernetes.io/part-of: prometheus-node-exporter
                 app.kubernetes.io/instance: node-exporter
                 app.kubernetes.io/name: prometheus-node-exporter
                 app.kubernetes.io/version: "1.3.1"
             annotations:
                 cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
           spec:
             automountServiceAccountToken: false
             serviceAccountName: node-exporter-prometheus-node-exporter
             securityContext:
               fsGroup: 65534
               runAsGroup: 65534
               runAsNonRoot: true
               runAsUser: 65534
             containers:
               - name: node-exporter
                 image: quay.io/prometheus/node-exporter:v1.3.1
                 imagePullPolicy: IfNotPresent
                 args:
                   - --path.procfs=/host/proc
                   - --path.sysfs=/host/sys
                   - --path.rootfs=/host/root
                   - --web.listen-address=[$(HOST_IP)]:9100
                 env:
                 - name: HOST_IP
                   value: 0.0.0.0
                 ports:
                   - name: metrics
                     containerPort: 9100
                     protocol: TCP
                 livenessProbe:
                   failureThreshold: 3
                   httpGet:
                     httpHeaders:
                     path: /
                     port: 9100
                     scheme: HTTP
                   initialDelaySeconds: 0
                   periodSeconds: 10
                   successThreshold: 1
                   timeoutSeconds: 1
                 readinessProbe:
                   failureThreshold: 3
                   httpGet:
                     httpHeaders:
                     path: /
                     port: 9100
                     scheme: HTTP
                   initialDelaySeconds: 0
                   periodSeconds: 10
                   successThreshold: 1
                   timeoutSeconds: 1
                 resources:
                    {}
                 volumeMounts:
                   - name: proc
                     mountPath: /host/proc
                     readOnly:  true
                   - name: sys
                     mountPath: /host/sys
                     readOnly: true
                   - name: root
                     mountPath: /host/root
                     mountPropagation: HostToContainer
                     readOnly: true
             hostNetwork: true
             hostPID: true
             tolerations:
               - effect: NoExecute
                 key: edgefarm.applications
                 operator: Exists
             volumes:
               - name: proc
                 hostPath:
                   path: /proc
               - name: sys
                 hostPath:
                   path: /sys
               - name: root
                 hostPath:
                   path: /
     - apiVersion: v1
       kind: Service
       metadata:
         name: node-exporter-prometheus-node-exporter
         namespace: nodegroup
         labels:            
           helm.sh/chart: prometheus-node-exporter-4.4.1
           app.kubernetes.io/managed-by: Helm
           app.kubernetes.io/component: metrics
           app.kubernetes.io/part-of: prometheus-node-exporter
           app.kubernetes.io/instance: node-exporter
           app.kubernetes.io/name: prometheus-node-exporter
           app.kubernetes.io/version: "1.3.1"
         annotations:
                  prometheus.io/scrape: "true"
       spec:
         type: ClusterIP
         ports:
           - port: 9100
             targetPort: 9100
             protocol: TCP
             name: metrics
         selector:           
           app.kubernetes.io/instance: node-exporter
           app.kubernetes.io/name: prometheus-node-exporter
  workloadScope:
    targetNodeGroups:
      - name: virtual-25af4f51
      - name: virtual-3da802e0
      - name: virtual-e2ddb58a
