kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  annotations:
    meta.helm.sh/release-name: node-exporter
  labels:
    app.kubernetes.io/managed-by: Helm
  name: node-exporter
  namespace: monitoring
spec:
  endpoints:
    - path: /metrics
      port: metrics
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/instance: node-exporter