apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-agent-yml
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    k8s-app: grafana-agent
data:
  agent.yaml: |
    server:
      log_level: info
    logs:
      configs:
      - name: default
        positions:
          filename: /tmp/positions.yaml
        target_config:
          sync_period: 10s
        scrape_configs:
          - job_name: system
            pipeline_stages:
            static_configs:
          - job_name: kernel
            static_configs:
              - targets: [localhost]
                labels:
                  job: kernel
                  host: ${NODE_NAME}
                  __path__: /var/log/kern.log
          - job_name: syslog
            static_configs:
              - targets: [localhost]
                labels:
                  job: syslog
                  host: ${NODE_NAME}
                  __path__: /var/log/syslog
          - job_name: journal
            journal:
              json: false
              max_age: 12h
              path: /var/log/journal
              labels:
                job: systemd-journal
            relabel_configs:
              - source_labels: ['__journal__systemd_unit']
                target_label: 'unit'
    metrics:
      global:
        scrape_interval: 5s
        remote_write:
          - url: {{ .Values.configmap.agent_yaml.global.remote_write }}
        external_labels:
          edge_node: ${NODE_NAME}
      configs:
        - name: edgenodes-exporter
          scrape_configs:
            - job_name: node_exporter
              static_configs:
                - targets: {{ .Values.configmap.agent_yaml.metrics.configs.edgenodes_exporter.scrape_configs.job.node_exporter.targets }}
              relabel_configs:
              - source_labels: [__address__]
                target_label: instance
                replacement: ${NODE_NAME}
              {{- if eq .Values.monitoring "default" }}
              metric_relabel_configs:
              - source_labels: [__name__]
                regex: '(.*load.*)|(.*hwmnon.*)|(.*cpu.*)|(.*memory.*)|(.*network.*)|(.*disk.*)|(.*filesystem.*)|(.*sockstat.*)|node_uname_info|node_time_seconds|node_boot_time_seconds'
                action: keep
              {{- end }}
          remote_write:
            - url: {{ .Values.configmap.agent_yaml.metrics.configs.edgenodes_exporter.remote_write.url }}
              basic_auth:
                username: ${MIMIR_AGENT_USERNAME}
                password: ${MIMIR_AGENT_PASSWORD}
