apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-agent-yml
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    k8s-app: grafana-agent
data:
  agent.yaml: |
    server:
      log_level: info
    metrics:
      global:
        scrape_interval: 1m
        remote_write:
          - url: {{ .Values.configmap.agent_yaml.global.remote_write }}
      configs:
        - name: default
          scrape_configs:
            - job_name: agent
              static_configs:
                - targets: {{ .Values.configmap.agent_yaml.config.targets }}
          remote_write:
            - url: {{ .Values.configmap.agent_yaml.remote_write }}