apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-agent-yml
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    k8s-app: grafana-agent
data:
  agent.yaml: |
    server:
      log_level: debug
    logs:
      configs:
      - name: default
        clients:
        - url: {{ .Values.configmap.agent_yaml.logs.configs.default.clients.url }}
          basic_auth:
            username: {{ .Values.configmap.agent_yaml.logs.configs.default.clients.basic_auth.username }}
            password: {{ .Values.configmap.agent_yaml.logs.configs.default.clients.basic_auth.password }}
          external_labels:
            edge_node: ${NODE_NAME}
        positions:
          filename: /tmp/positions.yaml
        target_config:
          sync_period: 10s
        scrape_configs:
          - job_name: system
            pipeline_stages:
            static_configs:
            - targets:
               - {{ .Values.configmap.agent_yaml.logs.configs.default.scrape_configs.job.system.targets }}
              labels:
               job: podlogs  # A `job` label is fairly standard in prometheus and useful for linking metrics and logs.
               host: ${NODE_NAME} # A `host` label will help identify logs from this machine vs others
               __path__: /var/log/pods/**/*.log  # The path matching uses a third party library: https://github.com/bmatcuk/doublestar
               __path_exclude__: /var/log/pods/**/*.log  # The path matching uses a third party library: https://github.com/bmatcuk/doublestar
          - job_name: kernel
            static_configs:
              - targets: [localhost]
                labels:
                  job: kernel
                  host: ${NODE_NAME}
                  __path__: /var/log/kern.log
          - job_name: syslog
            static_configs:
              - targets: [localhost]
                labels:
                  job: syslog
                  host: ${NODE_NAME}
                  __path__: /var/log/syslog
          - job_name: journal
            journal:
              json: false
              max_age: 12h
              path: /var/log/journal
              labels:
                job: systemd-journal
            relabel_configs:
              - source_labels: ['__journal__systemd_unit']
                target_label: 'unit'
    metrics:
      global:
        scrape_interval: 1m
        remote_write:
          - url: {{ .Values.configmap.agent_yaml.global.remote_write }}
        external_labels:
          edge_node: ${NODE_NAME}
      configs:
        - name: edgenodes-exporter
          scrape_configs:
            - job_name: node_exporter
              static_configs:
                - targets: {{ .Values.configmap.agent_yaml.metrics.configs.edgenodes_exporter.scrape_configs.job.node_exporter.targets }}
              relabel_configs:
              - source_labels: [__address__]
                target_label: instance
                replacement: ${NODE_NAME}
              {{- if eq .Values.monitoring "default" }}
              metric_relabel_configs:
              - source_labels: [__name__]
                regex: '(.*cpu.*)|(.*memory.*)|(.*network.*)|(.*disk.*)|(.*filesystem.*)|(.*sockstat.*)|node_uname_info'
                action: keep
              {{- end }}
            - job_name: cadvisor
              static_configs:
                - targets: {{ .Values.configmap.agent_yaml.metrics.configs.edgenodes_exporter.scrape_configs.job.cadvisor.targets }}
              relabel_configs:
              - source_labels: [__address__]
                target_label: instance
                replacement: ${NODE_NAME}
              {{- if eq .Values.monitoring "default" }}
              metric_relabel_configs:
              - source_labels: [__name__]
                regex: '(.*cpu.*)|(.*memory.*)|(.*network.*)|container_last_seen'
                action: keep
                {{- /*
                modify from which namespaces you don't want to collect metrics.
                */}}
              - source_labels: [container_label_io_kubernetes_pod_namespace] 
                regex: 'kubeedge|edge-monitoring'
                action: drop
              {{- end }}
            - job_name: leaf-nats
              static_configs:
                - targets: {{ .Values.configmap.agent_yaml.metrics.configs.edgenodes_exporter.scrape_configs.job.leaf_nats.targets }}
              relabel_configs:
              - source_labels: [__address__]
                target_label: instance
                replacement: ${NODE_NAME}
          remote_write:
            - url: {{ .Values.configmap.agent_yaml.metrics.configs.edgenodes_exporter.remote_write.url }}
              basic_auth:
                username: {{ .Values.configmap.agent_yaml.metrics.configs.edgenodes_exporter.remote_write.basic_auth.username }}
                password: {{ .Values.configmap.agent_yaml.metrics.configs.edgenodes_exporter.remote_write.basic_auth.password }}
