apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-agent-yml
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    k8s-app: grafana-agent
data:
  agent.yaml: |
    server:
      log_level: info
    metrics:
      global:
        scrape_interval: 1m
        remote_write:
          - url: {{ .Values.configmap.agent_yaml.global.remote_write }}
        external_labels:
          edge_node: ${NODE_NAME}
      configs:
        - name: node-exporter-edgenodes
          scrape_configs:
            - job_name: agent
              static_configs:
                - targets: {{ .Values.configmap.agent_yaml.config.job.grafana_agent.targets }}
              relabel_configs:
              - source_labels: [__address__]
                target_label: instance
                replacement: ${NODE_NAME}
            - job_name: cadvisor
              static_configs:
                - targets: {{ .Values.configmap.agent_yaml.config.job.cadvisor.targets }}
              relabel_configs:
              - source_labels: [__address__]
                target_label: instance
                replacement: ${NODE_NAME}
          remote_write:
            - url: {{ .Values.configmap.agent_yaml.config.remote_write.url }}
              basic_auth:
                username: {{ .Values.configmap.agent_yaml.config.remote_write.basic_auth.username }}
                password: {{ .Values.configmap.agent_yaml.config.remote_write.basic_auth.password }}
